/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package solucion;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;


/**
 *
 * @author Hp
 */
public class MetodoBurbuja extends javax.swing.JFrame {

     DefaultListModel modelo = new DefaultListModel();

    /**
     * Creates new form MetodoBurbuja
     */
    public MetodoBurbuja() {
        initComponents();
        qq.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNumeros = new javax.swing.JTextField();
        qw = new javax.swing.JScrollPane();
        modelo1= new DefaultListModel();
        lstNumerosOrdenados = new javax.swing.JPanel();
        qq = new javax.swing.JScrollPane();
        lstNumeros = new javax.swing.JPanel();
        cmdOrdenarNumeros = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumerosMouseClicked(evt);
            }
        });
        txtNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerosActionPerformed(evt);
            }
        });
        txtNumeros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumerosKeyPressed(evt);
            }
        });
        jPanel1.add(txtNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 70, -1));

        qw.setModel(modelo1);

        javax.swing.GroupLayout lstNumerosOrdenadosLayout = new javax.swing.GroupLayout(lstNumerosOrdenados);
        lstNumerosOrdenados.setLayout(lstNumerosOrdenadosLayout);
        lstNumerosOrdenadosLayout.setHorizontalGroup(
            lstNumerosOrdenadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        lstNumerosOrdenadosLayout.setVerticalGroup(
            lstNumerosOrdenadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        qw.setViewportView(lstNumerosOrdenados);

        jPanel1.add(qw, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 90, 230));

        javax.swing.GroupLayout lstNumerosLayout = new javax.swing.GroupLayout(lstNumeros);
        lstNumeros.setLayout(lstNumerosLayout);
        lstNumerosLayout.setHorizontalGroup(
            lstNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        lstNumerosLayout.setVerticalGroup(
            lstNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        qq.setViewportView(lstNumeros);

        jPanel1.add(qq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, 230));

        cmdOrdenarNumeros.setText("ORDENAR");
        cmdOrdenarNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOrdenarNumerosActionPerformed(evt);
            }
        });
        jPanel1.add(cmdOrdenarNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        cmdBorrar.setText("BORRAR");
        cmdBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdBorrarMouseClicked(evt);
            }
        });
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INGRESE LOS NUMEROS A ORDENAR:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ORDENAR NUMEROS CON EL MÉTODO BURBUJA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colores-mezclados-en-ondas_1920x1080_5844.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 380));

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerosActionPerformed

    private void cmdOrdenarNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOrdenarNumerosActionPerformed
        // TODO add your handling code here:
        int[]Numeros=new int[10];
        for (int i=0;i<qq.getModel().getSize(); i++){
            String S=qq.getModel().getElementAt(i);
            Numeros[i]=Integer.parseInt(S);
        }
        for(int i=0; i< Numeros.length-1; i++){
            for(int j=0; j< Numeros.length-1; j++){
                if (Numeros[j]<Numeros[j+1]){
                    int tmp = Numeros[j+1];
                    Numeros[j+1]=Numeros[j];
                    Numeros[j]=tmp;
                }
            }
        }
        modelo1.removeAllElements();
        for(int i=0;i<qq.getModel().getSize(); i++){
            modelo1.addElement(Numeros[i]);
        }

    }//GEN-LAST:event_cmdOrdenarNumerosActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtNumerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumerosMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNumerosMouseClicked

    private void txtNumerosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerosKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String N=txtNumeros.getText();
            modelo.addElement(N);
            txtNumeros.setText("");
        }

    }//GEN-LAST:event_txtNumerosKeyPressed

    private void cmdBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdBorrarMouseClicked
        // TODO add your handling code here:
        modelo.removeAllElements();
        modelo1.removeAllElements();
        txtNumeros.setText("");

    }//GEN-LAST:event_cmdBorrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodoBurbuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodoBurbuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodoBurbuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodoBurbuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodoBurbuja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdOrdenarNumeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel lstNumeros;
    private DefaultListModel modelo1;
    private javax.swing.JPanel lstNumerosOrdenados;
    private javax.swing.JScrollPane qq;
    private javax.swing.JScrollPane qw;
    private javax.swing.JTextField txtNumeros;
    // End of variables declaration//GEN-END:variables
}
