/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package colas;

import solucion.ColasS;
import solucion.Listas;
import solucion.PilasS;
import solucion.menuP;
import solucion.menuSeU3;

/**
 *
 * @author Hp
 */
public class ColasP extends javax.swing.JFrame {

    Metodos m = new Metodos();
    
    public ColasP() {
        initComponents();
        setResizable(false);
        setSize(1000, 500);
        // setLocation(20,50);
        setLocationRelativeTo(null);
        //setTitle("Hola");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDatos = new javax.swing.JTextField();
        AgregarElemento = new javax.swing.JButton();
        QuitarElemento = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Ib1 = new javax.swing.JLabel();
        Ib2 = new javax.swing.JLabel();
        Ib3 = new javax.swing.JLabel();
        Ib4 = new javax.swing.JLabel();
        Ib5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("COLAS PREDEFINIDAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        txtDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatosActionPerformed(evt);
            }
        });
        jPanel1.add(txtDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, 30));

        AgregarElemento.setBackground(new java.awt.Color(0, 204, 0));
        AgregarElemento.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        AgregarElemento.setForeground(new java.awt.Color(255, 255, 255));
        AgregarElemento.setText("PUSH");
        AgregarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarElementoActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        QuitarElemento.setBackground(new java.awt.Color(153, 0, 0));
        QuitarElemento.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        QuitarElemento.setForeground(new java.awt.Color(255, 255, 255));
        QuitarElemento.setText("POP");
        QuitarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarElementoActionPerformed(evt);
            }
        });
        jPanel1.add(QuitarElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        Eliminar.setBackground(new java.awt.Color(0, 204, 204));
        Eliminar.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("VACIAR");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        Area.setEditable(false);
        Area.setColumns(20);
        Area.setRows(5);
        jScrollPane1.setViewportView(Area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 150, 260));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Introducir elementos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("INSTRUCCIONES:\n\n1-Ingrese el dato\n2-De clikc a PUSH\n3-De click a POP para quitar un dato\n4-De click a vaciar para quitar todos los datos\n5-Repita los pasos las veces que quiera");
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 260, 170));

        Ib1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Ib1.setForeground(new java.awt.Color(255, 255, 255));
        Ib1.setText("PRIMER ELEMENTO: ");
        jPanel1.add(Ib1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        Ib2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Ib2.setForeground(new java.awt.Color(255, 255, 255));
        Ib2.setText("SEGUNDO ELEMENTOS:");
        jPanel1.add(Ib2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        Ib3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Ib3.setForeground(new java.awt.Color(255, 255, 255));
        Ib3.setText("TERCER ELEMENTO:");
        jPanel1.add(Ib3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));
        jPanel1.add(Ib4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 180, 20));
        jPanel1.add(Ib5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 180, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/optimista.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colores-mezclados-en-ondas_1920x1080_5844.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setForeground(new java.awt.Color(153, 0, 0));
        jMenu1.setText("MENU");

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setText("MENU PRINCIPAL");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem2.setText("MENU SECUNDARIO");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem3.setText("SALIR");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(153, 0, 0));
        jMenu2.setText("DESPLAZAMIENTO");

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(153, 0, 0));
        jMenuItem5.setText("COLAS PREDEFINIDAS");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem6.setText("LISTAS");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem4.setText("PILAS");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        dispose();
        new Listas().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      dispose();
      new menuSeU3().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
        new menuP().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       dispose();
        new ColasS().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        dispose();
        new PilasS().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void txtDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatosActionPerformed

    private void AgregarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarElementoActionPerformed
        if(!txtDatos.getText().equals("")){
           m.push(txtDatos.getText());
           Ib4.setText(m.EstaLlena());
           Ib5.setText(m.EstaVacia());
           act();
          
           
       }

    }//GEN-LAST:event_AgregarElementoActionPerformed

    private void QuitarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarElementoActionPerformed
        if(!txtDatos.getText().equals("")&&!Area.getText().equals("")){
                   m.Pop();
                   act();
               }
    }//GEN-LAST:event_QuitarElementoActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
                if(!txtDatos.getText().equals("")){
            m.VaciarCola();
            Ib1.setText("");
            Ib2.setText("");
            Ib3.setText("");
                    act();
           
        }
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColasP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColasP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColasP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColasP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColasP().setVisible(true);
            }
        });
    }
    public void act(){
    Area.setText(m.VerCola());
    Ib1.setText("Primero:"+m.Primero());
    Ib2.setText("Ultimo:"+m.Ultimo());
    Ib3.setText("Numero De Elementos:"+m.Elementos());


}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarElemento;
    private javax.swing.JTextArea Area;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel Ib1;
    private javax.swing.JLabel Ib2;
    private javax.swing.JLabel Ib3;
    private javax.swing.JLabel Ib4;
    private javax.swing.JLabel Ib5;
    private javax.swing.JButton QuitarElemento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtDatos;
    // End of variables declaration//GEN-END:variables

    
}
